// 9mm data only. The reusable generator lives in 00_ammo_framework.js.
global.createtaczrecipe.registerAmmo({
  key: "9mm",
  casingMold: "createtaczrecipe_9mm_casing",
  bulletMold: "createtaczrecipe_9mm_bullet",
  materials: { casing: { tag: "createtaczrecipe:metal_blanks/brass" }, bullet: { tag: "createtaczrecipe:metal_blanks/copper" } },
  counts: { casing: 1, roughBullet: 2 },
  casing: "createtaczrecipe:empty_9mm_casing",
  roughBullet: "createtaczrecipe:rough_9mm_bullet",
  polishedBullet: "createtaczrecipe:polished_9mm_bullet",
  primer: "createtaczrecipe:small_arms_primer",
  propellant: "createtaczrecipe:light_propellant_charge",
  transitional: "createtaczrecipe:incomplete_9mm_round",
  final: "tacz:ammo",
  ammoId: "tacz:9mm",
  polishing: { input: { item: "createtaczrecipe:rough_9mm_bullet" }, output: { id: "createtaczrecipe:polished_9mm_bullet" } },
  primerRecipe: { type: "create:pressing", ingredients: [{ tag: "c:nuggets/iron" }], results: [{ id: "createtaczrecipe:small_arms_primer", count: 10 }] },
  propellantRecipe: { type: "create:mixing", ingredients: [{ tag: "c:gunpowders" }], results: [{ id: "createtaczrecipe:light_propellant_charge", count: 25 }] },
  operations: [
    { type: "create:deploying", ingredients: [{ item: "createtaczrecipe:incomplete_9mm_round" }, { item: "createtaczrecipe:small_arms_primer" }], results: [{ id: "createtaczrecipe:incomplete_9mm_round" }] },
    { type: "create:deploying", ingredients: [{ item: "createtaczrecipe:incomplete_9mm_round" }, { item: "createtaczrecipe:light_propellant_charge" }], results: [{ id: "createtaczrecipe:incomplete_9mm_round" }] },
    { type: "create:deploying", ingredients: [{ item: "createtaczrecipe:incomplete_9mm_round" }, { item: "createtaczrecipe:polished_9mm_bullet" }], results: [{ id: "createtaczrecipe:incomplete_9mm_round" }] },
    { type: "create:pressing", ingredients: [{ item: "createtaczrecipe:incomplete_9mm_round" }], results: [{ id: "createtaczrecipe:incomplete_9mm_round" }] },
  ],
});
